### ISSUE TITLE
Step 2: Create blob storages to store:

### ISSUE THREAD

**Issue by ggorman** [devitocodes/daks#2]
* true model
* initial model

**Comment by navjotk** [comment]
Available at:
https://navdaks.blob.core.windows.net/models/overthrust_3D_initial_model.h5

and

https://navdaks.blob.core.windows.net/models/overthrust_3D_true_model_2D.h5

**Comment by navjotk** [comment]
Automated through [Makefile](https://github.com/devitocodes/daks/blob/master/Makefile) and [uploader.py](https://github.com/devitocodes/daks/blob/master/uploader.py)
