### ISSUE TITLE
Step 3: Use DAKS2 to generate shot records.

### ISSUE THREAD

**Issue by ggorman** [devitocodes/daks#3]
* Use blob storage to generate shot records.
* Use Dask to parallelize work.
* Use the elastic model to avoid inverse crime.

**Comment by mloubout** [comment]
>Use the elastic model to avoid inverse crime.

I appreciate the motivation and the will to be "non inverse crime", but this is borderline crazy to hope to get something like that work. Inverting acoustic data is hard enough, no need to do something that complicated. So would stick with inverse crime to avoid adding too much complexity to the exercise.

**Comment by navjotk** [comment]
Another option: use the TTI modelling operator to generate shots.

**Comment by navjotk** [comment]
For now, acoustic (inverse crime!) shots are available at: https://navdaks.blob.core.windows.net/shots/shot_0.h5 
upto
https://navdaks.blob.core.windows.net/shots/shot_9.h5

Uploading code to do this shortly

**Comment by navjotk** [comment]
[generate_shot_data.py](https://github.com/devitocodes/daks/blob/master/generate_shot_data.py) now uses the density formulation to generate shots straight to azure blob storage.
